/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import SceneKit;

@class AVTAvatarInstance;

@interface AVTAvatarView : SCNView
@property (nonatomic, retain) AVTAvatarInstance *avatarInstance;
@end
