/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;
#import "AVTAvatar.h"

@interface AVTAnimoji: AVTAvatar
+ (id)animojiNamed:(id)arg1;
+ (id)animojiNames;
+ (UIImage *)thumbnailForAnimojiNamed:(id)arg1 options:(id)arg2;
@end
