/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import SceneKit;
#import "AVTAnimoji.h"

@interface AVTView : SCNView
@property (nonatomic, retain) AVTAvatar *avatar;
@end
